#!/usr/bin/env python3

from subprocess import Popen, PIPE, DEVNULL
from argparse import ArgumentParser, RawTextHelpFormatter

parser = ArgumentParser(
    description=
    """
    Installer of mac-cleanup-py
    https://github.com/mac-cleanup/mac-cleanup-py
    """,
    formatter_class=RawTextHelpFormatter,
)

parser.add_argument('-i', '--install', help='Installs mac-cleanup-py',
                    action='store_true')
parser.add_argument('-u', '--uninstall', help='Uninstalls mac-cleanup-py',
                    action='store_true')

args = parser.parse_args()


def cmd(
        command: str,
) -> str:
    """
    Executes command in Popen
    Args:
        command: Bash command
    Returns: Stdout
    """
    return Popen(command, shell=True, stdout=PIPE, stderr=DEVNULL).communicate()[0].strip().decode('utf-8')


download_uri = 'https://raw.githubusercontent.com/mac-cleanup/mac-cleanup-py/main/mac-cleanup'


def install():
    cmd('python3 -m pip install requests -q')
    import requests

    print('Downloading mac-cleanup-py...')
    script = requests.get(download_uri).content
    with open('mac-cleanup', 'wb') as out:
        out.write(script)
    cmd('chmod +x mac-cleanup')
    print('Installing mac-cleanup-py...')
    cmd('sudo mv mac-cleanup /usr/local/bin/mac-cleanup')
    print('All done!')


def uninstall():
    print('Uninstalling mac-cleanup-py...')
    cmd('sudo rm -rf /usr/local/bin/mac-cleanup')
    print('All done!')


def main():
    if args.install:
        install()

    if args.uninstall:
        uninstall()


if __name__ == '__main__':
    main()
    exit(1)
