name: Tests

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

jobs:
  tests:
    strategy:
      matrix:
        os: [ macos-latest ]
        python-version: [ '3.10', '3.11', '3.12', '3.13' ]
        include:
          - os: macos-26
            python-version: 3.x
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python V${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox-gh-actions
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Tests with Tox
        run: tox
